name: Test Validation Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Check test results
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Test results indicate failures.. Please address the failures before resubmitting.."
            exit 1
